packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - esbuild
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - msgpackr-extract
  - sharp
  - '@remotion/compositor-linux-x64-gnu'
